[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "waitress-serve --host=0.0.0.0 --port=$PORT --threads=100 app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

